server:
  port : 8083

#microservices configuration
spring:
  application:
    name: fl-project-service
  #database configuration:mysql
  datasource:
    url: jdbc:mysql://localhost:3306/fl_projects?useSSL=false
    username: root
    password: 

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

db:
  queries:
    projects:
      insertProject: insert into projects(ClientId,ProjectName,ProjectDescription,IsConfidential,PaymentTypeId,BidStartDate,BidEndDate,MinPrice,MaxPrice) values(?,?,?,?,?,?,?,?,?)
      selectAllProject: select * from projects
      selectProjectByProjectId: select * from projects where projectid = ?
      updateProjectByProjectid: update project set projectName=?,projectDescription=?,paymentTypeId=?,minPrice=?,maxPrice=? where projectId=?
      deleteProjectByProjectid: delete from projects where projectId=?
    paymentType:
      insertPaymentType: insert into paymentType(paymentType)values(?)
      selectAllPaymentType: select * from paymentType
    rating:
      insertRating: insert into ratings (userId,projectId,ratingDescription,Rating) values (?,?,?,?)
      selectAllRating: select * from ratings
      selectRatingByRatingId: select * from ratings where ratingId = ?
      selectRatingByUserId: select * from ratings where userId = ?
      selectRatingByProjectId: select * from ratings where projectId = ?
      updateRatingByratingId: update ratings set ratingDescription = ?,Rating =? where ratingId =?
      removeRatingByRatingId: delete from ratings where ratingId =?