server:
  port : 8083

#microservices configuration
spring:
  application:
    name: fl-project-service
  #database configuration:mysql
  datasource:
    url: jdbc:mysql://localhost:3306/fl_projects?useSSL=false
    username: root
    password: 

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

db:
  queries:
    projects:
      insertProject: insert into projects(ClientId,ProjectName,ProjectDescription,IsConfidential,BidStartDate,BidEndDate,MinPrice,MaxPrice) values(?,?,?,?,?,?,?,?)
      selectAllProject: select * from projects
      selectProjectByProjectId: select * from projects where projectId = ?
      selectProjectByProjectIds: select * from projects where projectId in (%s)
      updateProjectByProjectId: update project set projectName=?,projectDescription=?,minPrice=?,maxPrice=? where projectId=?
      deleteProjectByProjectId: delete from projects where projectId=?
    paymentType:
      insertPaymentType: insert into paymentType(paymentType)values(?)
      selectAllPaymentType: select * from paymentType
    rating:
      insertRating: insert into ratings (userId,projectId,ratingDescription,Rating) values (?,?,?,?)
      selectAllRating: select * from ratings
      selectRatingByRatingId: select * from ratings where ratingId = ?
      selectRatingByUserId: select * from ratings where userId = ?
      selectRatingByProjectId: select * from ratings where projectId = ?
      updateRatingByRatingId: update ratings set ratingDescription = ?,Rating =? where ratingId =?
      removeRatingByRatingId: delete from ratings where ratingId =?
    projectAssignment:
      assignBid: insert into projectAssignment (bidId) values (?)


service:
  props:
    webServices:
      fl-skill-service:
        endpoint: http://localhost:8082/project-skills
      fl-bid-service:
        endpoint: http://localhost:8084/bids