server:
  port : 8081

#microservices configuration
spring:
  application:
    name: fl-user-service
  #database configuration:mysql
  datasource:
    url: jdbc:mysql://localhost:3306/fl_users?useSSL=false
    username: root
    password:

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

db:
  queries:
    users:
      insertUser: INSERT INTO users(Email) values(?)
      updateUser: UPDATE users set FirstName=?, LastName=?, Company=?, PhNo=?, PhotoURL=? WHERE UserId=?
      selectUser: Select * from users


