server:
  port : 8084

#microservices configuration
spring:
  application:
    name: fl-bid-service
  #database configuration:mysql
  datasource:
    url: jdbc:mysql://localhost:3306/fl_bids?useSSL=false
    username: root
    password:

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

db:
  queries:
    bid:
      insertBid: INSERT INTO bids(ProjectId,FreelancerId,Amount,DeliveryDays,Description) values (?,?,?,?,?)
      removeBid: DELETE FROM `bids` WHERE BidId=?
      updateBid: UPDATE bids set Amount= ? , DeliveryDays= ? , Description = ? WHERE BidId = ?
      selectAllBid: SELECT * from bids
      selectBidByBidId: SELECT * from bids WHERE BidId = ?
      selectBidByProjectId: SELECT * from bids WHERE ProjectId = ?
      getBidsByFreelancerIdAndStatus: SELECT * from bids WHERE FreelancerId = ? and status = ?
      getBidByFreelancerIdAndProjectId : SELECT * from bids WHERE ProjectId=? and FreelancerId=?
      approveBid: UPDATE bids set Status = ? WHERE BidId=?
      rejectBid: UPDATE bids set Status = ? WHERE ProjectId=? and BidId != ?


service:
  props:
    webServices:
      fl-user-service:
        endpoint: http://localhost:8081/users
      fl-project-service:
        endpoint: http://localhost:8083/projects