server:
  port : 8082

#microservices configuration
spring:
  application:
    name: fl-skill-service
  #database configuration:mysql
  datasource:
    url: jdbc:mysql://localhost:3306/fl_skills?useSSL=false
    username: root
    password: 

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/




app:
  file:
    upload-dir: ./fl-skill-service/uploads/files
    storage:
      mapping: file:~/fl-skill-service/uploads/

db:
  queries:
    categories:
      selectAllCategories: SELECT * FROM categories WHERE isDeleted=0
      selectCategoryById: SELECT * FROM categories WHERE isDeleted=0 and CategoryId = ?
      insertCategory: INSERT INTO categories (CategoryName) values (?)
      updateCategory: UPDATE categories set CategoryName = ? WHERE CategoryId = ?
      updateCategoryLogo: UPDATE categories set LogoURL = ? WHERE CategoryId = ?
      removeCategory: UPDATE categories set isDeleted = 1 WHERE CategoryId = ?