server:
  port : 8082

#microservices configuration
spring:
  application:
    name: fl-skill-service
  #database configuration:mysql
  datasource:
    url: jdbc:mysql://localhost:3306/fl_skills?useSSL=false
    username: root
    password: 

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/




app:
  file:
    upload-dir: ./fl-skill-service/uploads/files
    storage:
      mapping: file:~/fl-skill-service/uploads/

db:
  queries:
    categories:
      selectAllCategories: SELECT * FROM categories WHERE IsDeleted=0
      selectCategoryByCategoryId: SELECT * FROM categories WHERE IsDeleted=0 and CategoryId = ?
      insertCategory: INSERT INTO categories (CategoryName) values (?)
      updateCategory: UPDATE categories set CategoryName = ? WHERE CategoryId = ? and IsDeleted=0
      updateCategoryLogo: UPDATE categories set LogoURL = ? WHERE CategoryId = ? and IsDeleted=0
      removeCategoryByCategoryId: UPDATE categories set isDeleted = 1 WHERE CategoryId = ?
    skills:
      insertSkill: INSERT INTO skills(SkillName,CategoryId) values(?,?)
      selectAllSkills: SELECT * from skills WHERE IsDeleted=0
      selectSkillBySkillId: SELECT * from skills WHERE IsDeleted=0 and SkillId = ?
      selectSkillByCategory: SELECT * from skills WHERE IsDeleted=0 and CategoryId=?
      updateSkill: UPDATE skills set SkillName = ?, CategoryId=? WHERE SkillId= ? and IsDeleted=0
      removeSkillBySkillId: UPDATE skills set isDeleted = 1 WHERE skillId = ?
    projectSkills:
      insertProjectSkills: INSERT INTO projectskills (ProjectId,SkillId) values(?,?)
      selectProjectSkillsByProjectId: SELECT * from projectskills where ProjectId=?
      selectAllProject: SELECT  DISTINCT(ProjectId) from projectskills
      selectProjectByProjectId: SELECT  DISTINCT(ProjectId) from projectskills where ProjectId=?
    userSkills:
      insertUserSkills: INSERT INTO userskills (UserId,SkillId) values(?,?)
      selectUserSkillsByUserId: SELECT * from userskills where UserId=?
      selectUniqUserId: SELECT  DISTINCT(UserId) from userskills
      selectUniqUserIdByUserId: SELECT  DISTINCT(UserId) from userskills where UserId=?

